spring.application.name=tenant-care

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5433/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Hibernate/JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show.sql=true
spring.jpa.properties.hibernate.format_sql=true

#JWT Configuration
application.security.jwt.secret-key=${JWT_SECRET}